# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BxSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1)),
                ('img', models.ImageField(upload_to='/static/img/lbt/')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('href', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '首页轮播',
                'db_table': 'BxSlide',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='/static/img/icon/', verbose_name='图标')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('summary', models.TextField(default='summary', verbose_name='简介')),
            ],
            options={
                'verbose_name': '课程',
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('text', models.TextField(verbose_name='公告信息')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '最新公告',
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('name', models.CharField(max_length=32, verbose_name='活动名称')),
                ('detail', models.TextField(verbose_name='活动详情')),
                ('photo', models.ImageField(upload_to='/static/img/school_img/', verbose_name='活动照片')),
            ],
            options={
                'verbose_name': '校园活动',
                'db_table': 'SchoolActivity',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='姓名')),
                ('salary', models.IntegerField(verbose_name='薪资')),
                ('pic', models.ImageField(upload_to='/static/img/student_img/', verbose_name='头像')),
                ('company', models.CharField(max_length=50, verbose_name='就业单位')),
            ],
            options={
                'verbose_name': '学生信息',
                'db_table': 'StudentInfo',
            },
        ),
        migrations.CreateModel(
            name='StudentMoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('detail', models.TextField(verbose_name='个人简介')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.StudentInfo')),
            ],
            options={
                'verbose_name': '学生详情',
                'db_table': 'StudentMoreInfo',
            },
        ),
    ]
