# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='bxslide',
            name='img',
            field=models.ImageField(upload_to='static/img/lbt/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/icon/', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='pic',
            field=models.ImageField(upload_to='static/img/student_img/', verbose_name='头像'),
        ),
    ]
