# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180801_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolactivity',
            name='leader',
            field=models.CharField(default=1, max_length=20, verbose_name='负责人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='title',
            field=models.TextField(default=123, max_length='30', verbose_name='简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolactivity',
            name='photo',
            field=models.ImageField(upload_to='static/img/school_img/', verbose_name='活动照片'),
        ),
    ]
