# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180801_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='职位')),
                ('salary', models.IntegerField(verbose_name='薪资')),
                ('skill', models.TextField(verbose_name='能力要求')),
            ],
        ),
    ]
