# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180801_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.ImageField(default=0, upload_to='', verbose_name='权重')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '分类',
                'db_table': 'Classification',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('classification', models.ManyToManyField(to='app01.Classification')),
            ],
            options={
                'verbose_name_plural': '视频方向',
                'db_table': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态')),
                ('level', models.IntegerField(choices=[(1, '入门'), (2, '初级'), (3, '中级'), (4, '高级')], default=1, verbose_name='级别')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=32, verbose_name='简介')),
                ('img', models.ImageField(upload_to='static/img/video/', verbose_name='图片')),
                ('href', models.CharField(max_length=256, verbose_name='视频地址')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Classification')),
            ],
            options={
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AlterModelOptions(
            name='bxslide',
            options={'verbose_name_plural': '首页轮播'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': '招聘信息'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': '最新公告'},
        ),
        migrations.AlterModelOptions(
            name='schoolactivity',
            options={'verbose_name_plural': '校园活动'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterModelOptions(
            name='studentmoreinfo',
            options={'verbose_name_plural': '学生详情'},
        ),
    ]
