# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180802_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name_plural': '视频分类'},
        ),
        migrations.AlterField(
            model_name='classification',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='权重'),
        ),
    ]
